In [124]:
import pandas as pd

### Data Load & Inspect

In [125]:
df = pd.read_csv("C:\\python libraries\\CSV files\\owid-covid-data.csv")

In [126]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 429435 entries, 0 to 429434
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    429435 non-null  str
 1   continent                                   402910 non-null  str
 2   location                                    429435 non-null  str
 3   date                                        429435 non-null  str
 4   total_cases                                 411804 non-null  float64
 5   new_cases                                   410159 non-null  float64
 6   new_cases_smoothed                          408929 non-null  float64
 7   total_deaths                                411804 non-null  float64
 8   new_deaths                                  410608 non-null  float64
 9   new_deaths_smoothed                         409378 non-null  float64
 10  total_cases_per_million                     411804 non-null  float64
 11  new_cases_per_million                       410159 non-null  float64
 12  new_cases_smoothed_per_million              408929 non-null  float64
 13  total_deaths_per_million                    411804 non-null  float64
 14  new_deaths_per_million                      410608 non-null  float64
 15  new_deaths_smoothed_per_million             409378 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                39116 non-null   float64
 18  icu_patients_per_million                    39116 non-null   float64
 19  hosp_patients                               40656 non-null   float64
 20  hosp_patients_per_million                   40656 non-null   float64
 21  weekly_icu_admissions                       10993 non-null   float64
 22  weekly_icu_admissions_per_million           10993 non-null   float64
 23  weekly_hosp_admissions                      24497 non-null   float64
 24  weekly_hosp_admissions_per_million          24497 non-null   float64
 25  total_tests                                 79387 non-null   float64
 26  new_tests                                   75403 non-null   float64
 27  total_tests_per_thousand                    79387 non-null   float64
 28  new_tests_per_thousand                      75403 non-null   float64
 29  new_tests_smoothed                          103965 non-null  float64
 30  new_tests_smoothed_per_thousand             103965 non-null  float64
 31  positive_rate                               95927 non-null   float64
 32  tests_per_case                              94348 non-null   float64
 33  tests_units                                 106788 non-null  str
 34  total_vaccinations                          85417 non-null   float64
 35  people_vaccinated                           81132 non-null   float64
 36  people_fully_vaccinated                     78061 non-null   float64
 37  total_boosters                              53600 non-null   float64
 38  new_vaccinations                            70971 non-null   float64
 39  new_vaccinations_smoothed                   195029 non-null  float64
 40  total_vaccinations_per_hundred              85417 non-null   float64
 41  people_vaccinated_per_hundred               81132 non-null   float64
 42  people_fully_vaccinated_per_hundred         78061 non-null   float64
 43  total_boosters_per_hundred                  53600 non-null   float64
 44  new_vaccinations_smoothed_per_million       195029 non-null  float64
 45  new_people_vaccinated_smoothed              192177 non-null  float64
 46  new_people_vaccinated_smoothed_per_hundred  192177 non-null  float64
 47  stringency_index                            196190 non-null  float64
 48  population_density                          360492 non-null  float64
 49  median_age                                  334663 non-null  float64
 50  aged_65_older                               323270 non-null  float64
 51  aged_70_older                               331315 non-null  float64
 52  gdp_per_capita                              328292 non-null  float64
 53  extreme_poverty                             211996 non-null  float64
 54  cardiovasc_death_rate                       328865 non-null  float64
 55  diabetes_prevalence                         345911 non-null  float64
 56  female_smokers                              247165 non-null  float64
 57  male_smokers                                243817 non-null  float64
 58  handwashing_facilities                      161741 non-null  float64
 59  hospital_beds_per_thousand                  290689 non-null  float64
 60  life_expectancy                             390299 non-null  float64
 61  human_development_index                     319127 non-null  float64
 62  population                                  429435 non-null  int64
 63  excess_mortality_cumulative_absolute        13411 non-null   float64
 64  excess_mortality_cumulative                 13411 non-null   float64
 65  excess_mortality                            13411 non-null   float64
 66  excess_mortality_cumulative_per_million     13411 non-null   float64
dtypes: float64(61), int64(1), str(5)
memory usage: 219.5 MB

In [127]:
df.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths_per_million,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
count,4.118040e+05,4.101590e+05,4.089290e+05,4.118040e+05,410608.000000,409378.000000,411804.000000,410159.000000,408929.000000,411804.000000,...,243817.000000,161741.000000,290689.000000,390299.000000,319127.000000,4.294350e+05,1.341100e+04,13411.000000,13411.000000,13411.000000
mean,7.365292e+06,8.017360e+03,8.041026e+03,8.125957e+04,71.852139,72.060828,112096.199420,122.357073,122.713852,835.514337,...,33.097758,50.649390,3.106895,73.702098,0.722178,1.520336e+08,5.604765e+04,9.766431,10.925353,1772.666404
std,4.477582e+07,2.296649e+05,8.661611e+04,4.411901e+05,1368.322990,513.636565,162240.412405,1508.778585,559.701663,1134.932641,...,13.853952,31.905236,2.549168,7.387914,0.149237,6.975408e+08,1.568691e+05,12.040658,24.560706,1991.892770
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,7.700000,1.190000,0.100000,53.280000,0.390000,4.700000e+01,-3.772610e+04,-44.230000,-95.920000,-2936.450000
25%,6.280750e+03,0.000000e+00,0.000000e+00,4.300000e+01,0.000000,0.000000,1916.100000,0.000000,0.000000,24.570000,...,22.600000,20.860000,1.300000,69.500000,0.600000,5.237980e+05,1.765000e+02,2.060000,-1.500000,116.875000
50%,6.365300e+04,0.000000e+00,1.200000e+01,7.990000e+02,0.000000,0.000000,29145.480000,0.000000,2.790000,295.090000,...,33.100000,49.540000,2.500000,75.050000,0.740000,6.336393e+06,6.815200e+03,8.130000,5.660000,1270.800000
75%,7.582720e+05,0.000000e+00,3.132900e+02,9.574000e+03,0.000000,3.140000,156770.190000,0.000000,56.250000,1283.820000,...,41.500000,82.500000,4.210000,79.460000,0.830000,3.296952e+07,3.912804e+04,15.160000,15.575000,2883.025000
max,7.758668e+08,4.423623e+07,6.319461e+06,7.057132e+06,103719.000000,14817.000000,763598.600000,241758.230000,34536.890000,6601.110000,...,78.100000,100.000000,13.800000,86.750000,0.960000,7.975105e+09,1.349776e+06,78.080000,378.220000,10293.520000

In [128]:
df.head(5)

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN

In [129]:
df.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'stringency_index',
       'population_density', 'median_age', 'aged_65_older', 'aged_70_older',
       'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate',
       'diabetes_prevalence', 'female_smokers', 'male_smokers',
       'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index', 'population',
       'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative',
       'excess_mortality', 'excess_mortality_cumulative_per_million'],
      dtype='str')

In [130]:
df.shape

(429435, 67)

In [131]:
df.dtypes

iso_code                                       str
continent                                      str
location                                       str
date                                           str
total_cases                                float64
                                            ...
population                                   int64
excess_mortality_cumulative_absolute       float64
excess_mortality_cumulative                float64
excess_mortality                           float64
excess_mortality_cumulative_per_million    float64
Length: 67, dtype: object

In [132]:
df['location'].unique()

<StringArray>
[        'Afghanistan',              'Africa',             'Albania',
             'Algeria',      'American Samoa',             'Andorra',
              'Angola',            'Anguilla', 'Antigua and Barbuda',
           'Argentina',
 ...
             'Vatican',           'Venezuela',             'Vietnam',
               'Wales',   'Wallis and Futuna',      'Western Sahara',
               'World',               'Yemen',              'Zambia',
            'Zimbabwe']
Length: 255, dtype: str

In [133]:
df.isnull().sum()

iso_code                                        0
continent                                   26525
location                                        0
date                                            0
total_cases                                 17631
                                            ...
population                                      0
excess_mortality_cumulative_absolute       416024
excess_mortality_cumulative                416024
excess_mortality                           416024
excess_mortality_cumulative_per_million    416024
Length: 67, dtype: int64

In [134]:
filter = df[df['location'].isin(["India", "USA", "Brazil", "UK", "China"])]

In [135]:
filter

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
50234,BRA,South America,Brazil,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,...,17.9,NaN,2.20,75.88,0.76,215313504,NaN,NaN,NaN,NaN
50235,BRA,South America,Brazil,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,...,17.9,NaN,2.20,75.88,0.76,215313504,NaN,NaN,NaN,NaN
50236,BRA,South America,Brazil,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,...,17.9,NaN,2.20,75.88,0.76,215313504,NaN,NaN,NaN,NaN
50237,BRA,South America,Brazil,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,...,17.9,NaN,2.20,75.88,0.76,215313504,NaN,NaN,NaN,NaN
50238,BRA,South America,Brazil,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,...,17.9,NaN,2.20,75.88,0.76,215313504,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175226,IND,Asia,India,2024-08-08,NaN,NaN,NaN,NaN,NaN,NaN,...,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
175227,IND,Asia,India,2024-08-09,NaN,NaN,NaN,NaN,NaN,NaN,...,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
175228,IND,Asia,India,2024-08-10,NaN,NaN,NaN,NaN,NaN,NaN,...,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
175229,IND,Asia,India,2024-08-11,NaN,NaN,NaN,NaN,NaN,NaN,...,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN
175230,IND,Asia,India,2024-08-12,NaN,NaN,NaN,NaN,NaN,NaN,...,20.6,59.55,0.53,69.66,0.64,1417173120,NaN,NaN,NaN,NaN

In [136]:
filter['date'] = pd.to_datetime(filter['date'])

In [137]:
filter['date'].max()

Timestamp('2024-08-12 00:00:00')

In [138]:
filter['date'].min()

Timestamp('2020-01-05 00:00:00')

In [139]:
df = df[["date", "location", "total_cases", "new_cases", "total_deaths", "new_deaths", "total_vaccinations"]]

In [140]:
df = df.sort_values(["location", "date"])

In [141]:
cum_cols = ["total_cases",  "total_deaths", "total_vaccinations"]
df[cum_cols] = df.groupby("location")[cum_cols].ffill()

In [142]:
df = df.fillna(0)

In [143]:
df.isnull().sum()

date                  0
location              0
total_cases           0
new_cases             0
total_deaths          0
new_deaths            0
total_vaccinations    0
dtype: int64

In [144]:
pivot_table = pd.pivot_table(
    data=df,
    index="date",
    columns="location",
    values="new_cases",
)

In [145]:
pivot_table.shape

(1688, 255)

In [146]:
pivot_table1 = pd.pivot_table(
    data=df,
    index="date",
    columns="location",
    values="total_vaccinations",
)

In [147]:
pivot_table1.shape

(1688, 255)

In [148]:
total = df.groupby("location")[["total_cases", "total_deaths"]].max()
total

                total_cases  total_deaths
location
Afghanistan        235214.0        7998.0
Africa           13145380.0      259117.0
Albania            335047.0        3605.0
Algeria            272139.0        6881.0
American Samoa       8359.0          34.0
...                     ...           ...
Western Sahara          0.0           0.0
World           775866783.0     7057132.0
Yemen               11945.0        2159.0
Zambia             349842.0        4077.0
Zimbabwe           266386.0        5740.0

[255 rows x 2 columns]

In [149]:
death_rate = (df.groupby("location")[["total_deaths", "total_cases"]].max())

death_rate["Death_rate"] = (
    death_rate["total_deaths"] /
    death_rate["total_cases"] * 100
).round(2)

In [150]:
death_rate

                total_deaths  total_cases  Death_rate
location
Afghanistan           7998.0     235214.0        3.40
Africa              259117.0   13145380.0        1.97
Albania               3605.0     335047.0        1.08
Algeria               6881.0     272139.0        2.53
American Samoa          34.0       8359.0        0.41
...                      ...          ...         ...
Western Sahara           0.0          0.0         NaN
World              7057132.0  775866783.0        0.91
Yemen                 2159.0      11945.0       18.07
Zambia                4077.0     349842.0        1.17
Zimbabwe              5740.0     266386.0        2.15

[255 rows x 3 columns]

In [151]:
death_rate = death_rate.sort_values(by="Death_rate", ascending=False)

In [152]:
death_rate

                total_deaths  total_cases  Death_rate
location
Yemen                 2159.0      11945.0       18.07
Sudan                 5046.0      63993.0        7.89
Syria                 3163.0      57423.0        5.51
Somalia               1361.0      27334.0        4.98
Peru                220975.0    4526977.0        4.88
...                      ...          ...         ...
Scotland                 0.0          0.0         NaN
Taiwan                   0.0          0.0         NaN
Turkmenistan             0.0          0.0         NaN
Wales                    0.0          0.0         NaN
Western Sahara           0.0          0.0         NaN

[255 rows x 3 columns]

In [153]:
first_month = df.groupby("location").head(90)
last_month = df.groupby("location").tail(90)

In [154]:
growth = (
    first_month.groupby("location")["new_cases"].mean() /
    last_month.groupby("location")["new_cases"].mean()
).sort_values(ascending=False)

growth.idxmax()

'Afghanistan'